name: DangerJS

on: pull_request_target

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
        fetch-depth: 0
    - name: Use Node.js
      uses: actions/setup-node@v4.0.1
    - name: Install yarn dependencies
      run: |
        yarn install --frozen-lockfile
        yarn danger ci -d danger/dangerfile.ts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
