name: JSON diff

on: pull_request_target

jobs:
  json-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current version
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0
          path: current
      - name: Checkout old version
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          repository: ${{ github.event.pull_request.base.repo.full_name }}
          fetch-depth: 0
          path: old

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install graphtage

      - name: get graphtage diff
        id: graphtage
        run: |
          diff_output=$(graphtage --html --log-level CRITICAL old/Map/map.json current/Map/map.json | tail -n +9 | head -n -2)
          diff_output="${diff_output//'%'/'%25'}"
          diff_output="${diff_output//$'\n'/'%0A'}"
          diff_output="${diff_output//$'\r'/'%0D'}"
          echo "::set-output name=diff::${diff_output}"

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Textual map diff
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Textual map diff
            <details>
            <summary>Open to see the diff for commit ${{ github.event.pull_request.head.sha }}</summary>
            ${{ steps.graphtage.outputs.diff }}
            </details>
          edit-mode: replace