name: Map diffs

on: [pull_request_target]

jobs:
  map-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          fetch-depth: 0
          
      - name: Check if the map was changed in this PR
        id: map-change-detected
        uses: tj-actions/changed-files@v42.0.2
        with:
          # the only source of truth is the actual map
          files: Map/map
          sha: ${{github.event.pull_request.head.sha}}
          base_sha: ${{github.event.pull_request.base.sha}}
        
      - name: Create map diffs
        if: steps.map-change-detected.outputs.any_changed == 'true'
        uses: Delwing/mudlet-map-diff-action@details-tag-fix
        with:
          old-map: Map/map
          reuse-comment: true
          collapse-diff: true
        env:
          CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
          CLOUDINARY_KEY: ${{ secrets.CLOUDINARY_KEY }}
          CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}
