name: Map diffs

on: [pull_request]

jobs:
  map-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.base_ref}}
          path: 'base'
          
      - name: Check if the map was changed in this PR
        id: map-change-detected
        uses: tj-actions/changed-files@v11
        with:
          # the only source of truth is the actual map
          files: Map/map
        
      - name: Create map diffs
        if: steps.map-change-detected.outputs.any_changed == 'true'
        uses: Delwing/mudlet-map-diff-action@v1
        with:
          old-map: base/Map/map
          new-map: Map/map
        env:
          CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}
          CLOUDINARY_KEY: ${{ secrets.CLOUDINARY_KEY }}
          CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}
